server:
  Host: 0.0.0.0
  Port: 8080

postgres:
  Username: root
  Password: root
  Host: localhost
  Port: 5432
  Database: wb_db

stan:
  ClusterID: my-cluster
  ClientID: client-1
  ChannelName: event
