version: '3'

services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - network

  nats-streaming:
    command: [ "-cid", "${CLUSTER_ID}" ]
    build:
      context: ./docker/nats-streaming
      dockerfile: Dockerfile
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - network

networks:
  network:
    driver: bridge
