version: '3'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: wb_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - network

  redis:
    image: redis:7.2.3-alpine3.18
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - network

  nats-streaming:
    image: nats-streaming:0.25.6-alpine3.18
    command: [ "-cid", "my-cluster" ]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - network

networks:
  network:
    driver: bridge

