version: '3'

services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: wb_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    networks:
      - network

  nats-streaming:
    image: nats-streaming:0.25.6-alpine3.18
    command: [ "-cid", "my-cluster" ]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - network

networks:
  network:
    driver: bridge
